// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

#ifndef PROTOBUF_gps_2eproto__INCLUDED
#define PROTOBUF_gps_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace gps {
class Sample;
class SampleDefaultTypeInternal;
extern SampleDefaultTypeInternal _Sample_default_instance_;
}  // namespace gps

namespace gps {

namespace protobuf_gps_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gps_2eproto

enum SampleType {
  ACTION = 0,
  ACTION_V = 1,
  JOINT_ANGLES = 2,
  JOINT_VELOCITIES = 3,
  END_EFFECTOR_POINTS = 4,
  END_EFFECTOR_POINT_VELOCITIES = 5,
  END_EFFECTOR_POINT_JACOBIANS = 6,
  END_EFFECTOR_POINT_ROT_JACOBIANS = 7,
  END_EFFECTOR_POSITIONS = 8,
  END_EFFECTOR_ROTATIONS = 9,
  END_EFFECTOR_JACOBIANS = 10,
  END_EFFECTOR_HESSIANS = 11,
  RGB_IMAGE = 12,
  DEPTH_IMAGE = 13,
  RGB_IMAGE_SIZE = 14,
  CONTEXT_IMAGE = 15,
  CONTEXT_IMAGE_SIZE = 16,
  IMAGE_FEAT = 17,
  END_EFFECTOR_POINTS_NO_TARGET = 18,
  END_EFFECTOR_POINT_VELOCITIES_NO_TARGET = 19,
  NOISE = 20,
  TOTAL_DATA_TYPES = 21
};
bool SampleType_IsValid(int value);
const SampleType SampleType_MIN = ACTION;
const SampleType SampleType_MAX = TOTAL_DATA_TYPES;
const int SampleType_ARRAYSIZE = SampleType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SampleType_descriptor();
inline const ::std::string& SampleType_Name(SampleType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SampleType_descriptor(), value);
}
inline bool SampleType_Parse(
    const ::std::string& name, SampleType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SampleType>(
    SampleType_descriptor(), name, value);
}
enum ActuatorType {
  TRIAL_ARM = 0,
  AUXILIARY_ARM = 1,
  TOTAL_ACTUATOR_TYPES = 2
};
bool ActuatorType_IsValid(int value);
const ActuatorType ActuatorType_MIN = TRIAL_ARM;
const ActuatorType ActuatorType_MAX = TOTAL_ACTUATOR_TYPES;
const int ActuatorType_ARRAYSIZE = ActuatorType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ActuatorType_descriptor();
inline const ::std::string& ActuatorType_Name(ActuatorType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ActuatorType_descriptor(), value);
}
inline bool ActuatorType_Parse(
    const ::std::string& name, ActuatorType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ActuatorType>(
    ActuatorType_descriptor(), name, value);
}
enum PositionControlMode {
  NO_CONTROL = 0,
  JOINT_SPACE = 1,
  TASK_SPACE = 2,
  TOTAL_CONTROL_MODES = 3
};
bool PositionControlMode_IsValid(int value);
const PositionControlMode PositionControlMode_MIN = NO_CONTROL;
const PositionControlMode PositionControlMode_MAX = TOTAL_CONTROL_MODES;
const int PositionControlMode_ARRAYSIZE = PositionControlMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* PositionControlMode_descriptor();
inline const ::std::string& PositionControlMode_Name(PositionControlMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    PositionControlMode_descriptor(), value);
}
inline bool PositionControlMode_Parse(
    const ::std::string& name, PositionControlMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PositionControlMode>(
    PositionControlMode_descriptor(), name, value);
}
enum ControllerType {
  LIN_GAUSS_CONTROLLER = 0,
  CAFFE_CONTROLLER = 1,
  TF_CONTROLLER = 2,
  TOTAL_CONTROLLER_TYPES = 3
};
bool ControllerType_IsValid(int value);
const ControllerType ControllerType_MIN = LIN_GAUSS_CONTROLLER;
const ControllerType ControllerType_MAX = TOTAL_CONTROLLER_TYPES;
const int ControllerType_ARRAYSIZE = ControllerType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ControllerType_descriptor();
inline const ::std::string& ControllerType_Name(ControllerType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ControllerType_descriptor(), value);
}
inline bool ControllerType_Parse(
    const ::std::string& name, ControllerType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ControllerType>(
    ControllerType_descriptor(), name, value);
}
// ===================================================================

class Sample : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gps.Sample) */ {
 public:
  Sample();
  virtual ~Sample();

  Sample(const Sample& from);

  inline Sample& operator=(const Sample& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Sample(Sample&& from) noexcept
    : Sample() {
    *this = ::std::move(from);
  }

  inline Sample& operator=(Sample&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sample& default_instance();

  static inline const Sample* internal_default_instance() {
    return reinterpret_cast<const Sample*>(
               &_Sample_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Sample* other);
  friend void swap(Sample& a, Sample& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Sample* New() const PROTOBUF_FINAL { return New(NULL); }

  Sample* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Sample& from);
  void MergeFrom(const Sample& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Sample* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float X = 6 [packed = true];
  int x_size() const;
  void clear_x();
  static const int kXFieldNumber = 6;
  float x(int index) const;
  void set_x(int index, float value);
  void add_x(float value);
  const ::google::protobuf::RepeatedField< float >&
      x() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_x();

  // repeated float U = 7 [packed = true];
  int u_size() const;
  void clear_u();
  static const int kUFieldNumber = 7;
  float u(int index) const;
  void set_u(int index, float value);
  void add_u(float value);
  const ::google::protobuf::RepeatedField< float >&
      u() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_u();

  // repeated float V = 8 [packed = true];
  int v_size() const;
  void clear_v();
  static const int kVFieldNumber = 8;
  float v(int index) const;
  void set_v(int index, float value);
  void add_v(float value);
  const ::google::protobuf::RepeatedField< float >&
      v() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_v();

  // repeated float obs = 9 [packed = true];
  int obs_size() const;
  void clear_obs();
  static const int kObsFieldNumber = 9;
  float obs(int index) const;
  void set_obs(int index, float value);
  void add_obs(float value);
  const ::google::protobuf::RepeatedField< float >&
      obs() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_obs();

  // repeated float meta = 10 [packed = true];
  int meta_size() const;
  void clear_meta();
  static const int kMetaFieldNumber = 10;
  float meta(int index) const;
  void set_meta(int index, float value);
  void add_meta(float value);
  const ::google::protobuf::RepeatedField< float >&
      meta() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_meta();

  // optional uint32 dX = 2;
  bool has_dx() const;
  void clear_dx();
  static const int kDXFieldNumber = 2;
  ::google::protobuf::uint32 dx() const;
  void set_dx(::google::protobuf::uint32 value);

  // optional uint32 dU = 3;
  bool has_du() const;
  void clear_du();
  static const int kDUFieldNumber = 3;
  ::google::protobuf::uint32 du() const;
  void set_du(::google::protobuf::uint32 value);

  // optional uint32 dV = 4;
  bool has_dv() const;
  void clear_dv();
  static const int kDVFieldNumber = 4;
  ::google::protobuf::uint32 dv() const;
  void set_dv(::google::protobuf::uint32 value);

  // optional uint32 dO = 5;
  bool has_do_() const;
  void clear_do_();
  static const int kDOFieldNumber = 5;
  ::google::protobuf::uint32 do_() const;
  void set_do_(::google::protobuf::uint32 value);

  // optional uint32 T = 1 [default = 100];
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  ::google::protobuf::uint32 t() const;
  void set_t(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gps.Sample)
 private:
  void set_has_t();
  void clear_has_t();
  void set_has_dx();
  void clear_has_dx();
  void set_has_du();
  void clear_has_du();
  void set_has_dv();
  void clear_has_dv();
  void set_has_do_();
  void clear_has_do_();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > x_;
  mutable int _x_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > u_;
  mutable int _u_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > v_;
  mutable int _v_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > obs_;
  mutable int _obs_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > meta_;
  mutable int _meta_cached_byte_size_;
  ::google::protobuf::uint32 dx_;
  ::google::protobuf::uint32 du_;
  ::google::protobuf::uint32 dv_;
  ::google::protobuf::uint32 do__;
  ::google::protobuf::uint32 t_;
  friend struct protobuf_gps_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Sample

// optional uint32 T = 1 [default = 100];
inline bool Sample::has_t() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Sample::set_has_t() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Sample::clear_has_t() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Sample::clear_t() {
  t_ = 100u;
  clear_has_t();
}
inline ::google::protobuf::uint32 Sample::t() const {
  // @@protoc_insertion_point(field_get:gps.Sample.T)
  return t_;
}
inline void Sample::set_t(::google::protobuf::uint32 value) {
  set_has_t();
  t_ = value;
  // @@protoc_insertion_point(field_set:gps.Sample.T)
}

// optional uint32 dX = 2;
inline bool Sample::has_dx() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sample::set_has_dx() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sample::clear_has_dx() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sample::clear_dx() {
  dx_ = 0u;
  clear_has_dx();
}
inline ::google::protobuf::uint32 Sample::dx() const {
  // @@protoc_insertion_point(field_get:gps.Sample.dX)
  return dx_;
}
inline void Sample::set_dx(::google::protobuf::uint32 value) {
  set_has_dx();
  dx_ = value;
  // @@protoc_insertion_point(field_set:gps.Sample.dX)
}

// optional uint32 dU = 3;
inline bool Sample::has_du() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Sample::set_has_du() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Sample::clear_has_du() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Sample::clear_du() {
  du_ = 0u;
  clear_has_du();
}
inline ::google::protobuf::uint32 Sample::du() const {
  // @@protoc_insertion_point(field_get:gps.Sample.dU)
  return du_;
}
inline void Sample::set_du(::google::protobuf::uint32 value) {
  set_has_du();
  du_ = value;
  // @@protoc_insertion_point(field_set:gps.Sample.dU)
}

// optional uint32 dV = 4;
inline bool Sample::has_dv() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Sample::set_has_dv() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Sample::clear_has_dv() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Sample::clear_dv() {
  dv_ = 0u;
  clear_has_dv();
}
inline ::google::protobuf::uint32 Sample::dv() const {
  // @@protoc_insertion_point(field_get:gps.Sample.dV)
  return dv_;
}
inline void Sample::set_dv(::google::protobuf::uint32 value) {
  set_has_dv();
  dv_ = value;
  // @@protoc_insertion_point(field_set:gps.Sample.dV)
}

// optional uint32 dO = 5;
inline bool Sample::has_do_() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Sample::set_has_do_() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Sample::clear_has_do_() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Sample::clear_do_() {
  do__ = 0u;
  clear_has_do_();
}
inline ::google::protobuf::uint32 Sample::do_() const {
  // @@protoc_insertion_point(field_get:gps.Sample.dO)
  return do__;
}
inline void Sample::set_do_(::google::protobuf::uint32 value) {
  set_has_do_();
  do__ = value;
  // @@protoc_insertion_point(field_set:gps.Sample.dO)
}

// repeated float X = 6 [packed = true];
inline int Sample::x_size() const {
  return x_.size();
}
inline void Sample::clear_x() {
  x_.Clear();
}
inline float Sample::x(int index) const {
  // @@protoc_insertion_point(field_get:gps.Sample.X)
  return x_.Get(index);
}
inline void Sample::set_x(int index, float value) {
  x_.Set(index, value);
  // @@protoc_insertion_point(field_set:gps.Sample.X)
}
inline void Sample::add_x(float value) {
  x_.Add(value);
  // @@protoc_insertion_point(field_add:gps.Sample.X)
}
inline const ::google::protobuf::RepeatedField< float >&
Sample::x() const {
  // @@protoc_insertion_point(field_list:gps.Sample.X)
  return x_;
}
inline ::google::protobuf::RepeatedField< float >*
Sample::mutable_x() {
  // @@protoc_insertion_point(field_mutable_list:gps.Sample.X)
  return &x_;
}

// repeated float U = 7 [packed = true];
inline int Sample::u_size() const {
  return u_.size();
}
inline void Sample::clear_u() {
  u_.Clear();
}
inline float Sample::u(int index) const {
  // @@protoc_insertion_point(field_get:gps.Sample.U)
  return u_.Get(index);
}
inline void Sample::set_u(int index, float value) {
  u_.Set(index, value);
  // @@protoc_insertion_point(field_set:gps.Sample.U)
}
inline void Sample::add_u(float value) {
  u_.Add(value);
  // @@protoc_insertion_point(field_add:gps.Sample.U)
}
inline const ::google::protobuf::RepeatedField< float >&
Sample::u() const {
  // @@protoc_insertion_point(field_list:gps.Sample.U)
  return u_;
}
inline ::google::protobuf::RepeatedField< float >*
Sample::mutable_u() {
  // @@protoc_insertion_point(field_mutable_list:gps.Sample.U)
  return &u_;
}

// repeated float V = 8 [packed = true];
inline int Sample::v_size() const {
  return v_.size();
}
inline void Sample::clear_v() {
  v_.Clear();
}
inline float Sample::v(int index) const {
  // @@protoc_insertion_point(field_get:gps.Sample.V)
  return v_.Get(index);
}
inline void Sample::set_v(int index, float value) {
  v_.Set(index, value);
  // @@protoc_insertion_point(field_set:gps.Sample.V)
}
inline void Sample::add_v(float value) {
  v_.Add(value);
  // @@protoc_insertion_point(field_add:gps.Sample.V)
}
inline const ::google::protobuf::RepeatedField< float >&
Sample::v() const {
  // @@protoc_insertion_point(field_list:gps.Sample.V)
  return v_;
}
inline ::google::protobuf::RepeatedField< float >*
Sample::mutable_v() {
  // @@protoc_insertion_point(field_mutable_list:gps.Sample.V)
  return &v_;
}

// repeated float obs = 9 [packed = true];
inline int Sample::obs_size() const {
  return obs_.size();
}
inline void Sample::clear_obs() {
  obs_.Clear();
}
inline float Sample::obs(int index) const {
  // @@protoc_insertion_point(field_get:gps.Sample.obs)
  return obs_.Get(index);
}
inline void Sample::set_obs(int index, float value) {
  obs_.Set(index, value);
  // @@protoc_insertion_point(field_set:gps.Sample.obs)
}
inline void Sample::add_obs(float value) {
  obs_.Add(value);
  // @@protoc_insertion_point(field_add:gps.Sample.obs)
}
inline const ::google::protobuf::RepeatedField< float >&
Sample::obs() const {
  // @@protoc_insertion_point(field_list:gps.Sample.obs)
  return obs_;
}
inline ::google::protobuf::RepeatedField< float >*
Sample::mutable_obs() {
  // @@protoc_insertion_point(field_mutable_list:gps.Sample.obs)
  return &obs_;
}

// repeated float meta = 10 [packed = true];
inline int Sample::meta_size() const {
  return meta_.size();
}
inline void Sample::clear_meta() {
  meta_.Clear();
}
inline float Sample::meta(int index) const {
  // @@protoc_insertion_point(field_get:gps.Sample.meta)
  return meta_.Get(index);
}
inline void Sample::set_meta(int index, float value) {
  meta_.Set(index, value);
  // @@protoc_insertion_point(field_set:gps.Sample.meta)
}
inline void Sample::add_meta(float value) {
  meta_.Add(value);
  // @@protoc_insertion_point(field_add:gps.Sample.meta)
}
inline const ::google::protobuf::RepeatedField< float >&
Sample::meta() const {
  // @@protoc_insertion_point(field_list:gps.Sample.meta)
  return meta_;
}
inline ::google::protobuf::RepeatedField< float >*
Sample::mutable_meta() {
  // @@protoc_insertion_point(field_mutable_list:gps.Sample.meta)
  return &meta_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace gps

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::gps::SampleType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gps::SampleType>() {
  return ::gps::SampleType_descriptor();
}
template <> struct is_proto_enum< ::gps::ActuatorType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gps::ActuatorType>() {
  return ::gps::ActuatorType_descriptor();
}
template <> struct is_proto_enum< ::gps::PositionControlMode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gps::PositionControlMode>() {
  return ::gps::PositionControlMode_descriptor();
}
template <> struct is_proto_enum< ::gps::ControllerType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gps::ControllerType>() {
  return ::gps::ControllerType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gps_2eproto__INCLUDED
