/**
 * @file config_loader.cpp
 * @brief Implementation of configuration loader and presets.
 */

#include "config_loader.h"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <regex>

namespace gps {
namespace config {

// ============================================================================
// ConfigLoader Implementation
// ============================================================================

ExperimentConfig ConfigLoader::load(const std::string& filepath) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot open config file: " + filepath);
    }

    std::stringstream buffer;
    buffer << file.rdbuf();
    return parse(buffer.str());
}

ExperimentConfig ConfigLoader::parse(const std::string& content) {
    ExperimentConfig config;
    std::istringstream stream(content);
    std::string line;
    std::string current_section;

    while (std::getline(stream, line)) {
        line = trim(line);

        // Skip empty lines and comments
        if (line.empty() || line[0] == '#') continue;

        // Check for section header (ends with :)
        if (line.back() == ':' && line.find(':') == line.length() - 1) {
            current_section = line.substr(0, line.length() - 1);
            continue;
        }

        // Parse key: value
        size_t colon_pos = line.find(':');
        if (colon_pos == std::string::npos) continue;

        std::string key = trim(line.substr(0, colon_pos));
        std::string value = trim(line.substr(colon_pos + 1));

        // Apply to appropriate section
        if (current_section == "common") {
            if (key == "experiment_name") config.common.experiment_name = value;
            else if (key == "conditions") config.common.conditions = parse_int(value);
            else if (key == "mode") config.common.mode = value;
            else if (key == "gamma") config.common.gamma = parse_double(value);
        } else if (current_section == "agent") {
            if (key == "type") config.agent.type = value;
            else if (key == "T") config.agent.T = parse_int(value);
            else if (key == "dt") config.agent.dt = parse_double(value);
            else if (key == "conditions") config.agent.conditions = parse_int(value);
        } else if (current_section == "algorithm") {
            if (key == "type") config.algorithm.type = value;
            else if (key == "iterations") config.algorithm.iterations = parse_int(value);
            else if (key == "kl_step") config.algorithm.kl_step = parse_double(value);
        } else if (current_section == "cost") {
            if (key == "gamma") config.algorithm.cost.gamma = parse_double(value);
            else if (key == "mode") config.algorithm.cost.mode = value;
            else if (key == "action_weight") config.algorithm.cost.action_weight = parse_double(value);
            else if (key == "state_weight") config.algorithm.cost.state_weight = parse_double(value);
        } else if (current_section.empty()) {
            // Top-level settings
            if (key == "iterations") config.iterations = parse_int(value);
            else if (key == "num_samples") config.num_samples = parse_int(value);
            else if (key == "gui_on") config.gui_on = (value == "true" || value == "1");
        }
    }

    return config;
}

void ConfigLoader::save(const ExperimentConfig& config, const std::string& filepath) {
    std::ofstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot write config file: " + filepath);
    }
    file << to_yaml(config);
}

std::string ConfigLoader::to_yaml(const ExperimentConfig& config) {
    std::ostringstream ss;

    ss << "# GPS Experiment Configuration\n";
    ss << "# Generated by C++ GPS Algorithm\n\n";

    ss << "iterations: " << config.iterations << "\n";
    ss << "num_samples: " << config.num_samples << "\n";
    ss << "verbose_trials: " << config.verbose_trials << "\n";
    ss << "gui_on: " << (config.gui_on ? "true" : "false") << "\n\n";

    ss << "common:\n";
    ss << "  experiment_name: " << config.common.experiment_name << "\n";
    ss << "  conditions: " << config.common.conditions << "\n";
    ss << "  mode: " << config.common.mode << "\n";
    ss << "  gamma: " << config.common.gamma << "\n\n";

    ss << "agent:\n";
    ss << "  type: " << config.agent.type << "\n";
    ss << "  world: " << config.agent.world << "\n";
    ss << "  T: " << config.agent.T << "\n";
    ss << "  dt: " << config.agent.dt << "\n";
    ss << "  conditions: " << config.agent.conditions << "\n";
    ss << "  sensor_dims:\n";
    ss << "    joint_angles: " << config.agent.sensor_dims.joint_angles << "\n";
    ss << "    joint_velocities: " << config.agent.sensor_dims.joint_velocities << "\n";
    ss << "    end_effector_points: " << config.agent.sensor_dims.end_effector_points << "\n";
    ss << "    action: " << config.agent.sensor_dims.action << "\n\n";

    ss << "algorithm:\n";
    ss << "  type: " << config.algorithm.type << "\n";
    ss << "  iterations: " << config.algorithm.iterations << "\n";
    ss << "  kl_step: " << config.algorithm.kl_step << "\n";
    ss << "  min_step_mult: " << config.algorithm.min_step_mult << "\n";
    ss << "  max_step_mult: " << config.algorithm.max_step_mult << "\n\n";

    ss << "cost:\n";
    ss << "  mode: " << config.algorithm.cost.mode << "\n";
    ss << "  gamma: " << config.algorithm.cost.gamma << "\n";
    ss << "  action_weight: " << config.algorithm.cost.action_weight << "\n";
    ss << "  state_weight: " << config.algorithm.cost.state_weight << "\n\n";

    ss << "dynamics:\n";
    ss << "  type: " << config.algorithm.dynamics.type << "\n";
    ss << "  regularization: " << config.algorithm.dynamics.regularization << "\n";

    return ss.str();
}

double ConfigLoader::parse_double(const std::string& value) {
    return std::stod(value);
}

int ConfigLoader::parse_int(const std::string& value) {
    return std::stoi(value);
}

Vector ConfigLoader::parse_vector(const std::string& value) {
    // Parse "[1.0, 2.0, 3.0]" format
    std::string cleaned = value;
    cleaned.erase(std::remove(cleaned.begin(), cleaned.end(), '['), cleaned.end());
    cleaned.erase(std::remove(cleaned.begin(), cleaned.end(), ']'), cleaned.end());

    std::vector<double> values;
    std::istringstream ss(cleaned);
    std::string item;
    while (std::getline(ss, item, ',')) {
        values.push_back(std::stod(trim(item)));
    }

    Vector vec(values.size());
    for (size_t i = 0; i < values.size(); ++i) {
        vec(static_cast<int>(i)) = values[i];
    }
    return vec;
}

std::string ConfigLoader::trim(const std::string& str) {
    size_t start = str.find_first_not_of(" \t\r\n");
    size_t end = str.find_last_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    return str.substr(start, end - start + 1);
}

// ============================================================================
// ExperimentPresets Implementation
// ============================================================================

ExperimentConfig ExperimentPresets::box2d_arm_example() {
    return ExperimentConfig::create_box2d_mdgps(1.0, "protagonist");
}

ExperimentConfig ExperimentPresets::box2d_pointmass_example() {
    auto config = ExperimentConfig::create_box2d_mdgps(1.0, "protagonist");
    config.common.experiment_name = "box2d_pointmass_example";
    return config;
}

ExperimentConfig ExperimentPresets::box2d_mdgps_protagonist() {
    return ExperimentConfig::create_box2d_mdgps(1.0, "protagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e0() {
    return ExperimentConfig::create_box2d_mdgps(1e0, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e2() {
    return ExperimentConfig::create_box2d_mdgps(1e2, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e4() {
    return ExperimentConfig::create_box2d_mdgps(1e4, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e6() {
    return ExperimentConfig::create_box2d_mdgps(1e6, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e8() {
    return ExperimentConfig::create_box2d_mdgps(1e8, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e_2() {
    return ExperimentConfig::create_box2d_mdgps(1e-2, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e_4() {
    return ExperimentConfig::create_box2d_mdgps(1e-4, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e_6() {
    return ExperimentConfig::create_box2d_mdgps(1e-6, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1e_8() {
    return ExperimentConfig::create_box2d_mdgps(1e-8, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y0_5() {
    return ExperimentConfig::create_box2d_mdgps(0.5, "antagonist");
}

ExperimentConfig ExperimentPresets::box2d_mdgps_y1_5() {
    return ExperimentConfig::create_box2d_mdgps(1.5, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_example() {
    return ExperimentConfig::create_mjc_mdgps(1.0, "protagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_example() {
    return ExperimentConfig::create_mjc_mdgps(1.0, "protagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_idg() {
    return ExperimentConfig::create_mjc_mdgps(1.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y0_5() {
    return ExperimentConfig::create_mjc_mdgps(0.5, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1() {
    return ExperimentConfig::create_mjc_mdgps(1.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y2() {
    return ExperimentConfig::create_mjc_mdgps(2.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y3() {
    return ExperimentConfig::create_mjc_mdgps(3.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y5() {
    return ExperimentConfig::create_mjc_mdgps(5.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y7() {
    return ExperimentConfig::create_mjc_mdgps(7.0, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e_1() {
    return ExperimentConfig::create_mjc_mdgps(1e-1, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e_2() {
    return ExperimentConfig::create_mjc_mdgps(1e-2, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e_4() {
    return ExperimentConfig::create_mjc_mdgps(1e-4, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e_5() {
    return ExperimentConfig::create_mjc_mdgps(1e-5, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e_6() {
    return ExperimentConfig::create_mjc_mdgps(1e-6, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e8() {
    return ExperimentConfig::create_mjc_mdgps(1e8, "antagonist");
}

ExperimentConfig ExperimentPresets::mjc_mdgps_antagonist_y1e10() {
    return ExperimentConfig::create_mjc_mdgps(1e10, "antagonist");
}

ExperimentConfig ExperimentPresets::get(const std::string& name) {
    static const std::map<std::string, ExperimentConfig(*)()> presets = {
        {"box2d_arm_example", box2d_arm_example},
        {"box2d_pointmass_example", box2d_pointmass_example},
        {"box2d_mdgps_protagonist", box2d_mdgps_protagonist},
        {"box2d_mdgps_y1e0", box2d_mdgps_y1e0},
        {"box2d_mdgps_y1e2", box2d_mdgps_y1e2},
        {"box2d_mdgps_y1e4", box2d_mdgps_y1e4},
        {"box2d_mdgps_y1e6", box2d_mdgps_y1e6},
        {"box2d_mdgps_y1e8", box2d_mdgps_y1e8},
        {"box2d_mdgps_y1e-2", box2d_mdgps_y1e_2},
        {"box2d_mdgps_y1e-4", box2d_mdgps_y1e_4},
        {"box2d_mdgps_y1e-6", box2d_mdgps_y1e_6},
        {"box2d_mdgps_y1e-8", box2d_mdgps_y1e_8},
        {"box2d_mdgps_y0.5", box2d_mdgps_y0_5},
        {"box2d_mdgps_y1.5", box2d_mdgps_y1_5},
        {"mjc_example", mjc_example},
        {"mjc_mdgps_example", mjc_mdgps_example},
        {"mjc_mdgps_idg", mjc_mdgps_idg},
        {"mjc_mdgps_antagonist_y0.5", mjc_mdgps_antagonist_y0_5},
        {"mjc_mdgps_antagonist_y1", mjc_mdgps_antagonist_y1},
        {"mjc_mdgps_antagonist_y2", mjc_mdgps_antagonist_y2},
        {"mjc_mdgps_antagonist_y3", mjc_mdgps_antagonist_y3},
        {"mjc_mdgps_antagonist_y5", mjc_mdgps_antagonist_y5},
        {"mjc_mdgps_antagonist_y7", mjc_mdgps_antagonist_y7},
        {"mjc_mdgps_antagonist_y1e-1", mjc_mdgps_antagonist_y1e_1},
        {"mjc_mdgps_antagonist_y1e-2", mjc_mdgps_antagonist_y1e_2},
        {"mjc_mdgps_antagonist_y1e-4", mjc_mdgps_antagonist_y1e_4},
        {"mjc_mdgps_antagonist_y1e-5", mjc_mdgps_antagonist_y1e_5},
        {"mjc_mdgps_antagonist_y1e-6", mjc_mdgps_antagonist_y1e_6},
        {"mjc_mdgps_antagonist_y1e8", mjc_mdgps_antagonist_y1e8},
        {"mjc_mdgps_antagonist_y1e10", mjc_mdgps_antagonist_y1e10},
    };

    auto it = presets.find(name);
    if (it == presets.end()) {
        throw std::invalid_argument("Unknown preset: " + name);
    }
    return it->second();
}

std::vector<std::string> ExperimentPresets::list() {
    return {
        "box2d_arm_example",
        "box2d_pointmass_example",
        "box2d_mdgps_protagonist",
        "box2d_mdgps_y1e0",
        "box2d_mdgps_y1e2",
        "box2d_mdgps_y1e4",
        "box2d_mdgps_y1e6",
        "box2d_mdgps_y1e8",
        "box2d_mdgps_y1e-2",
        "box2d_mdgps_y1e-4",
        "box2d_mdgps_y1e-6",
        "box2d_mdgps_y1e-8",
        "box2d_mdgps_y0.5",
        "box2d_mdgps_y1.5",
        "mjc_example",
        "mjc_mdgps_example",
        "mjc_mdgps_idg",
        "mjc_mdgps_antagonist_y0.5",
        "mjc_mdgps_antagonist_y1",
        "mjc_mdgps_antagonist_y2",
        "mjc_mdgps_antagonist_y3",
        "mjc_mdgps_antagonist_y5",
        "mjc_mdgps_antagonist_y7",
        "mjc_mdgps_antagonist_y1e-1",
        "mjc_mdgps_antagonist_y1e-2",
        "mjc_mdgps_antagonist_y1e-4",
        "mjc_mdgps_antagonist_y1e-5",
        "mjc_mdgps_antagonist_y1e-6",
        "mjc_mdgps_antagonist_y1e8",
        "mjc_mdgps_antagonist_y1e10",
    };
}

}  // namespace config
}  // namespace gps
